spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/thundercoin_incubadora
    username: postgres
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop